version: '3.8'

services:
  node1:
    build: .
    image: my-gluster-cluster-x64  
    container_name: node1
    privileged: true
    volumes:
      - node1-brick:/data/brick
    networks:
      - gluster-net
    tty: true

  node2:
    build: .
    image: my-gluster-cluster-x64 
    container_name: node2
    privileged: true
    volumes:
      - node2-brick:/data/brick
    networks:
      - gluster-net
    tty: true

  node3:
    build: .
    image: my-gluster-cluster-x64  
    container_name: node3
    privileged: true
    volumes:
      - node3-brick:/data/brick
    networks:
      - gluster-net
    tty: true

  node4:
    build: .
    image: my-gluster-cluster-x64  
    container_name: node4
    privileged: true
    volumes:
      - node4-brick:/data/brick
    networks:
      - gluster-net
    tty: true

volumes:
  node1-brick:
    driver: local
  node2-brick:
    driver: local
  node3-brick:
    driver: local
  node4-brick:
    driver: local

networks:
  gluster-net:
    driver: bridge